# EDA of combined energy demand and weather data

## Load and combine dataset

In [18]:
import pandas as pd

df_energy = pd.read_csv("../data/energy_demand_de_2019_2025.csv", parse_dates=['DateUTC'])
df_weather_all = pd.read_csv("../data/weather_data_mean_cities_2019_2025.csv", parse_dates=['DateUTC'])

# combine energy demand data with weather data, and save the combined dataset for future use
df_energy_weather = pd.concat([df_energy, df_weather_all], axis=1)
df_energy_weather = df_energy_weather.loc[:,~df_energy_weather.columns.duplicated()]
df_energy_weather.to_csv("../data/energy_weather_2019_2025.csv", index=False)

df_energy_weather.head()

,DateUTC,DateShort,EnergyDemand,year,hour,weekday,month,is_weekend,temperature_2m,rain,snowfall,wind_speed_10m,shortwave_radiation
0,2019-01-01 00:00:00,2019-01-01,41653.9575,2019,0,1,1,0,5.88,0.00,0.0,13.66,0.0
1,2019-01-01 01:00:00,2019-01-01,40113.5800,2019,1,1,1,0,5.86,0.00,0.0,14.04,0.0
2,2019-01-01 02:00:00,2019-01-01,39312.9375,2019,2,1,1,0,6.42,0.04,0.0,15.10,0.0
3,2019-01-01 03:00:00,2019-01-01,39097.1625,2019,3,1,1,0,6.28,0.02,0.0,16.46,0.0
4,2019-01-01 04:00:00,2019-01-01,38634.3500,2019,4,1,1,0,6.08,0.02,0.0,17.84,0.0

In [19]:
display(df_energy_weather.describe())
display(df_energy_weather.info())

,DateUTC,EnergyDemand,year,hour,weekday,month,is_weekend,temperature_2m,rain,snowfall,wind_speed_10m,shortwave_radiation
count,59160,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000,59160.000000
mean,2022-05-17 11:30:00.365111808,54663.227387,2021.888032,11.500101,2.999189,6.355375,0.285598,11.192025,0.092372,0.003722,11.963479,137.640429
min,2019-01-01 00:00:00,30908.880000,2019.000000,0.000000,0.000000,1.000000,0.000000,-9.960000,0.000000,0.000000,2.400000,0.000000
25%,2020-09-08 05:45:00,46803.277500,2020.000000,5.750000,1.000000,3.000000,0.000000,5.220000,0.000000,0.000000,8.440000,0.000000
50%,2022-05-17 11:30:00,54517.358750,2022.000000,11.500000,3.000000,6.000000,0.000000,10.800000,0.000000,0.000000,10.840000,8.800000
75%,2024-01-23 17:15:00,62177.330000,2024.000000,17.250000,5.000000,9.000000,1.000000,16.860000,0.100000,0.000000,14.340000,228.800000
max,2025-09-30 23:00:00,81077.455000,2025.000000,23.000000,6.000000,12.000000,1.000000,36.160000,3.760000,0.728000,40.920000,885.600000
std,NaN,9666.896304,1.949594,6.922113,2.000017,3.396644,0.451703,7.546550,0.200856,0.021976,4.956194,200.475408

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59160 entries, 0 to 59159
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DateUTC              59160 non-null  datetime64[ns]
 1   DateShort            59160 non-null  object
 2   EnergyDemand         59160 non-null  float64
 3   year                 59160 non-null  int64
 4   hour                 59160 non-null  int64
 5   weekday              59160 non-null  int64
 6   month                59160 non-null  int64
 7   is_weekend           59160 non-null  int64
 8   temperature_2m       59160 non-null  float64
 9   rain                 59160 non-null  float64
 10  snowfall             59160 non-null  float64
 11  wind_speed_10m       59160 non-null  float64
 12  shortwave_radiation  59160 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(5), object(1)
memory usage: 5.9+ MB

None